% defaultReconcileParams.m
%
%      usage: defaultReconcileParams(groupName,params,data)
%         by: justin gardner
%       date: 03/13/07
%    purpose: A default params reconcile. This does not necessarily
%             have to be called for params created by mrParamsDialog,
%             but if it is, then there will be a paramInfo field (for format
%             see wiki), and variables will be validated against that structure
%
function [params data] = defaultReconcileParams(groupName,params,data)

% check arguments
if ~any(nargin == [2 3])
  help defaultReconcileParams
  return
end

if ieNotDefined('data'),data=[];,end

% if params is a cell array, then call defaultReconcileParams on each
% element of the cell array one at a time
if iscell(params)
  for i = 1:length(params)
    if ~isempty(params{i})
      if length(data) >= i
	[params{i} data{i}] = defaultReconcileParams(groupName,params{i},data{i});
      else
	params{i} = defaultReconcileParams(groupName,params{i});
      end
    end
  end
  return
end

% get group name
if ieNotDefined('groupName')
  if isfield(params,'groupName')
    groupName = params.groupName;
  else
    groupName = '';
  end
end
% set group number
if ~ieNotDefined('groupName')
  groupNum = viewGet([],'groupNum',groupName);
end

% if this has the field paramInfo then it comes from'
% mrDefaultParamsGUI and we can check the parameters 
% for consistency
params = checkParams(params);

% look for a description, and see if it has something like [x...x], that should be replaced by the scan numbers selected in scanList and groupName 
params = fixDescription(params);

% get scan numbers
if isfield(params,'scanList')
  scanNums = params.scanList;
elseif isfield(params,'scanNum')
  scanNums = params.scanNum;
end

if ~ieNotDefined('scanNums') && ~ieNotDefined('groupNum')
  % if we don't have a tseriesFile field then generate it
  % this will usually happen the first time this function
  % is called on some params
  if ~isfield(params,'tseriesFile')
    % get the tseries name
    for iscan = 1:length(scanNums)
      params.tseriesFile{iscan} = viewGet([],'tseriesFile',scanNums(iscan),groupNum);
    end
  % the second time through, we will have tseriesFile
  % so now we have to get the correct scan numbers for those
  % tseriesFiles.
  else
    % starting values
    newScanNums = [];
    newdata = cell(1,viewGet([],'numScans',groupNum));
    newScanParams = cell(1,viewGet([],'numScans',groupNum));
    newd = cell(1,viewGet([],'numScans',groupNum));
    % see if the tseriesFile name matches
    for tnum = 1:length(params.tseriesFile)
      % get the scan number associated with the tseriesFile
      thisScanNum = viewGet([],'scanNum',params.tseriesFile{tnum},groupNum);
      % check for empty
      if isempty(thisScanNum)
	disp(sprintf('(defaultReconcileParams) Ignoring scan with tseriesFilename: %s because it no longer exists',params.tseriesFile{tnum}));
      else
	% found it, set the scan number
	newScanNums(end+1) = thisScanNum;
	% if there is scan params field then fix that
	if isfield(params,'scanParams')
	  newScanParams{thisScanNum} = params.scanParams{scanNums(tnum)};
	end
	% if there is a d field then fix that
	if isfield(params,'d')
	  newd{thisScanNum} = params.d{scanNums(tnum)};
	end
	% and if there is data, fix the data.
	if ~isempty(data)
	  newdata{end+1} = data{tnum};
	end
      end
    end
    % reset the scan field
    if isfield(params,'scanList')
      params.scanList = newScanNums;
    elseif isfield(params,'scanNum')
      params.scanNum = newScanNums;
    end
    % and reset the data
    if ~isempty(data)
      data = newdata;
    end
    % and reset the scanParams
    if isfield(params,'scanParams')
      params.scanParams = newScanParams;
    end
    % and reset the d field
    if isfield(params,'d')
      params.d = newd;
    end
  end  
end

% if there is a field called scanParams then reconcile those as well
if isfield(params,'scanParams') && iscell(params.scanParams)
  defaultReconcileParams(groupName,params.scanParams);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% function to check params generated by mrParamsDialog
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function params = checkParams(params)

if isfield(params,'paramInfo')
  [vars varinfo] = mrParamsParse(params.paramInfo);
  for i = 1:length(varinfo)
    useDefault = 0;
    % make sure the field exists
    if ~isfield(params,varinfo{i}.name)
      useDefault = 1;
    % check if it is good
    else
      % is it numeric
      if strcmp(lower(varinfo{i}.type),'numeric')
	if ~isnumeric(params.(varinfo{i}.name))
	  useDefault = 1;
	end
	% also check if there is a minmax
	if isfield(varinfo{i},'minmax')
	  if params.(varinfo{i}.name) < varinfo{i}.minmax(1)
	    disp(sprintf('(defaultReconcileParams) %s out of range. Setting to min=%f',varinfo{i}.name,varinfo.minmax(1)));
	    params.(varinfo{i}.name) = varinfo{i}.minmax(1);
	  elseif params.(varinfo{i}.name) > varinfo{i}.minmax(2)
	    disp(sprintf('(defaultReconcileParams) %s out of range. Setting to max=%f',varinfo{i}.name,varinfo.minmax(2)));
	    params.(varinfo{i}.name) = varinfo{i}.minmax(2);
	  end
	end
      % or a checkbox
      elseif strcmp(lower(varinfo{i}.type),'checkbox')
	if ~any(params.(varinfo{i}.name) == [0 1])
	  useDefault = 1;
	end
      end
    end      
    % see if we have to switch it to default
    if useDefault
      % make sure it is not a contingent value that has been shut
      % off, first get value it is contingent on
      if isfield(varinfo{i},'contingent')
	if isfield(params,varinfo{varinfo{i}.contingentOn}.name)
	  contingentValue = params.(varinfo{varinfo{i}.contingentOn}.name);
	else
	  contingentValue = varinfo{varinfo{i}.contingentOn}.value;
	  if iscell(contingentValue)
	    contingentValue = contingentValue{1};
	  end
	end
	if isstr(contingentValue),contingentValue = str2num(contingentValue);,end
	% if it has been shut down, give the parameter an empty
        % value and continue on
	if contingentValue==0
	  params.(varinfo{i}.name) = [];
	  continue
	end
      end
      % otherwise set the parameter to the default value
      if ~iscell(varinfo{i}.value)
	params.(varinfo{i}.name) = varinfo{i}.value;
      else
	params.(varinfo{i}.name) = varinfo{i}.value{1};
      end
      if isnumeric(params.(varinfo{i}.name))
	disp(sprintf('(defaultReconcileParams) Using default value for %s (%s)',varinfo{i}.name,num2str(params.(varinfo{i}.name))));
      else
	disp(sprintf('(defaultReconcileParams) Using default value for %s (%s)',varinfo{i}.name,params.(varinfo{i}.name)));
      end
    end
  end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% function to fix description field to contain
% info about group and scans
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function params = fixDescription(params)

if isfield(params,'description') && ~isempty(strfind(params.description,'[x...x]'))
  swaploc = strfind(params.description,'[x...x]');
  swaploc = swaploc(1);
  % get the group name
  if isfield(params,'groupName')
    groupName = params.groupName;
  else
    groupName = '';
  end
  % scan numbers
  if isfield(params,'scanList')
    scanNames = num2str(params.scanList);
  elseif isfield(params,'scanNum')
    scanNames = num2str(params.scanNum);
  else
    scanNames = '';
  end
  % now make the description string
  if ~isempty(groupName)
    params.description = sprintf('%s%s:%s%s',params.description(1:swaploc-1),groupName,scanNames,params.description(swaploc+7:end));
  else
    params.description = sprintf('%s%s%s',params.description(1:swaploc-1),scanNames,params.description(swaploc+7:end));
  end
end
